config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'posts/new'
  get 'posts/create'
  get 'posts/show'
  # Login routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Signup route
  get 'signup', to: 'users#new'

  # User resources
  resources :users, only: [:new, :create, :show]
  resources :posts, only: [:new, :create, :show, :edit, :update]

  # Blog posts
  get "/blog_posts/:id", to: "blog_posts#show"

  # Root path
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
end

app/models/post.rb
# app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts, dependent: :destroy
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
  end
  

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
    def index
        @blog_posts = BlogPost.all  #instanace variable 
    end 

    def show 
        @blog_posts = BlogPost.find(params[:id])
    end
end

app/controllers/home_controller.rb
# app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.includes(:user).all
  end
end

app/controllers/posts_controller.rb
# app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created!"
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
# app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully'
    else
      flash.now[:alert] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out successfully'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blog_posts/index.html.erb
<h1>MY blogs</h1>

<% @blog_posts.each do |blog_post| %>
    <div>
        <h2><%= blog_post.title %></h2>
        <p><%= blog_post.body %></p>
    </div>
<% end %>

app/views/blog_posts/show.html.erb
<h1><%= @blog_post.title%></h1>
<p><%= @blog_post.body%></p>

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb -->
<h1>All Blog Posts</h1>
<% @posts.each do |post| %>
  <div class="post">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <p><%= truncate(post.content, length: 100) %></p>
    <p><%= time_ago_in_words(post.created_at) %> ago</p>
    <p>Posted by: <%= link_to post.user.name, user_path(post.user) %></p>
    <%= link_to 'Read more', post_path(post), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
<%= stylesheet_link_tag 'posts', media: 'all', 'data-turbo-track': 'reload' %>
<%= stylesheet_link_tag 'home', media: 'all', 'data-turbo-track': 'reload' %>

</head>

<body>
  <nav>
    <div class="navbar">
      <div class="navbar-brand">
        <%= link_to 'Home', root_path %>
      </div>
      <div class="navbar-menu">
        <% if logged_in? %>
          <%= link_to '+ Add Post', new_post_path, class: 'nav-link' %>
          <%= link_to 'Profile', user_path(current_user), class: 'nav-link' %>
          <%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %>
        <% else %>
          <%= link_to 'Login', login_path, class: 'nav-link' %>
          <%= link_to 'Signup', signup_path, class: 'nav-link' %>
        <% end %>
      </div>
    </div>
  </nav>

  <%= yield %>

  <% flash.each do |type, message| %>
    <div class="flash-message flash-<%= type %>">
      <%= message %>
    </div>
  <% end %>
</body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/new.html.erb
<!-- app/views/posts/new.html.erb -->
<%= form_with(model: @post, local: true, class: "new_post") do |form| %>
<h1>New Post</h1>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div>
    <%= form.submit 'Create Post' %>
  </div>
<% end %>

app/views/posts/show.html.erb
<!-- app/views/posts/show.html.erb -->
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>

<% if logged_in? && @post.user == current_user %>
  <%= link_to 'Edit Post', edit_post_path(@post), class: 'btn btn-primary' %> |
  <%= link_to 'Back', root_path, class: 'btn btn-secondary' %>
<% else %>
  <%= link_to 'Back', root_path, class: 'btn btn-secondary' %>
<% end %>

app/views/users/new.html.erb
<div class="login-container">

<h1>Sign up</h1>

<%= form_with(model: @user, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Create my account", class: "btn btn-primary" %>
  </div>
<% end %>
<div>